version: '3.9'

networks:
  elasticsearch:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch-node
    hostname: elasticsearch-node
    restart: unless-stopped
    environment:
      - "ELASTICSEARCH_ENROLLMENT_TOKEN=eyJ2ZXIiOiI4LjEwLjQiLCJhZHIiOlsiMTkyLjE2OC4xOTIuMjo5MjAwIl0sImZnciI6ImI2MmIxMzM5ZjE2NDE0ZDc1MzQ2NjZhYzkwOTUzYjRjZTIxZjNiOWE4Y2ZhMTA3ZmYzOWNhODAwZTY5NjViODIiLCJrZXkiOiJuRFZZTG8wQmVsczZHeDdLNzlfZjpjVzR3S0FBelE4eW5maHdoaFJaVWVnIn0="
    volumes:
      - elasticsearch-data:/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  elasticsearch-data:
    driver: local
