version: '3.9'

networks:
  elasticsearch:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch-node
    hostname: elasticsearch-node
    restart: unless-stopped
    volumes:
      - elasticsearch-data:/elasticsearch/data
      - /config/certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  elasticsearch-data:
    driver: local
