version: '3.9'

networks:
  elasticsearch:
    driver: bridge

services:
  ngrok_elasticsearch:
    image: wernight/ngrok
    restart: unless-stopped
    hostname: ngrok_elasticsearch
    container_name: ngrok_elasticsearch
    command: >
      ngrok http https://elasticsearch-node:9200 -authtoken=2b6H4dh1PBgx1o1l1Xl0W9cZhl5_2AvNdHVqTaeurHPrcSiMM
    networks:
      - elasticsearch
    ports:
      - "5000:4040"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      retries: 120