version: '3.1'

networks:
  elasticsearch:
    driver: bridge

services:
  ngrok_elasticsearch:
    image: wernight/ngrok
    restart: unless-stopped
    container_name: ngrok_elasticsearch_1
    hostname: ngrok_elasticsearch_1
    command: >
      ngrok http http://elasticsearch -authtoken=2b6H4dh1PBgx1o1l1Xl0W9cZhl5_2AvNdHVqTaeurHPrcSiMM
    networks:
      - elasticsearch
    ports:
      - "5100:4040"