version: '3.9'

services:
  es-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    hostname: es-node-1
    environment:
      - node.name=es-node-1
      - cluster.name=dataindex-elk
      - discovery.seed_hosts=es-node-1,es-node-2
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - node.roles=master,data,ingest
      - network.host=0.0.0.0
      - http.port=9200
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-node-1/es-node-1.key
      - xpack.security.http.ssl.certificate=certs/es-node-1/es-node-1.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-node-1/es-node-1.key
      - xpack.security.transport.ssl.certificate=certs/es-node-1/es-node-1.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    volumes:
      - es-node-1-data:/usr/share/elasticsearch/data
      - /etc/elasticsearch/certs:/usr/share/elasticsearch/config/certs
    networks:
      - es_cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - node.hostname == ns558722

  es-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    hostname: es-node-2
    environment:
      - node.name=es-node-2
      - cluster.name=dataindex-elk
      - discovery.seed_hosts=es-node-1,es-node-2
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - node.roles=master,data,ingest
      - network.host=0.0.0.0
      - http.port=9200
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-node-2/es-node-2.key
      - xpack.security.http.ssl.certificate=certs/es-node-2/es-node-2.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-node-2/es-node-2.key
      - xpack.security.transport.ssl.certificate=certs/es-node-2/es-node-2.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    volumes:
      - es-node-2-data:/usr/share/elasticsearch/data
      - /etc/elasticsearch/certs:/usr/share/elasticsearch/config/certs
    networks:
      - es_cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      placement:
        constraints:
          - node.hostname == ns565591

  es-ngrok-1:
    image: wernight/ngrok
    hostname: es-ngrok-1
    environment:
      - NGROK_TOKEN=${NGROK_TOKEN_ES}
    command: >
      ngrok http https://es-node-1:9200 -authtoken=${NGROK_TOKEN_ES} --region=us --hostname=dataindex-elk-1.ngrok.app'
    networks:
      - es_cluster
    depends_on:
      - es-node-1
    ports:
      - "5000:4040"
    deploy:
      placement:
        constraints:
          - node.hostname == ns558722

  es-ngrok-2:
    image: wernight/ngrok
    hostname: es-ngrok-2
    environment:
      - NGROK_TOKEN=${NGROK_TOKEN_ES}
    command: >
      ngrok http https://es-node-2:9200 -authtoken=${NGROK_TOKEN_ES} --region=us --hostname=dataindex-elk-2.ngrok.app'
    networks:
      - es_cluster
    depends_on:
      - es-node-2
    ports:
      - "5100:4040"
    deploy:
      placement:
        constraints:
          - node.hostname == ns565591
volumes:
  es-node-1-data:
  es-node-2-data:
    
networks:
  es_cluster:
    external: true
