version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: ${ES_NODE}
    hostname: ${ES_NODE}
    restart: unless-stopped
    environment:
      - node.name=${ES_NODE}
      - cluster.name=${ES_CLUSTER}
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - discovery.seed_hosts=192.168.0.102,192.168.0.103
      - ELASTIC_PASSWORD=123456
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es_network
      
volumes:
  elasticsearch-data:
    driver: local

networks:
  es_network:
    external: true