cluster.name: "dataindex"

#----------------------- BEGIN SECURITY AUTO CONFIGURATION -----------------------
#
# The following settings, TLS certificates, and keys have been automatically      
# generated to configure Elasticsearch security features on 21-01-2024 18:36:06
#
# --------------------------------------------------------------------------------

# Enable security features
xpack.security.enabled: true
xpack.security.enrollment.enabled: true

# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12

# Enable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12
#----------------------- END SECURITY AUTO CONFIGURATION -------------------------

# Node role settings
node.name: node-1
node.roles: [master, data, ingest]
network.host: 0.0.0.0  # Ou o IP específico da máquina

# Cluster discovery settings
discovery.seed_hosts: ["192.168.0.100", "192.168.0.101"]
cluster.initial_master_nodes: ["node-1", "node-2"]

# Path settings for data and logs
# path.data: /path/to/data
# path.logs: /path/to/logs

# Monitoring settings
xpack.monitoring.collection.enabled: true

# Repository settings for backup
# path.repo: ["/path/to/repo"]
