node.name: es-node-1
cluster.name: es-datashelf
cluster.initial_master_nodes:
  - es-node-1
  - es-node-2
discovery.seed_hosts: 192.168.0.101
node.roles: [master, data, ingest]
network.host: "0.0.0.0"
http.port: 9200

# ---------------------- Security Settings ----------------------

bootstrap.memory_lock: true
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: "certs/es-node-1/es-node-1.key"
xpack.security.http.ssl.certificate: "certs/es-node-1/es-node-1.crt"
xpack.security.http.ssl.certificate_authorities: "certs/ca/ca.crt"
xpack.security.http.ssl.verification_mode: "certificate"
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: "certs/es-node-1/es-node-1.key"
xpack.security.transport.ssl.certificate: "certs/es-node-1/es-node-1.crt"
xpack.security.transport.ssl.certificate_authorities: "certs/ca/ca.crt"
xpack.security.transport.ssl.verification_mode: "certificate"
xpack.license.self_generated.type: "basic"
